# Operating system (build VM template)
os: Visual Studio 2015

# clone directory
clone_folder: c:\projects\OpenRTM-aist

install:
# by default, all script lines are interpreted as batch

build:
  build.bat

# scripts to run before build
before_build:
  - set PYTHON_DIR=C:\Python27
  - set PYTHONPATH=%PYTHON_DIR%\Lib
  - set OMNI_VERSION=4.2.1
  - cd c:\projects
  - ps: Start-FileDownload 'http://openrtm.org/pub/omniORB/win32/omniORB-4.2.1/omniORB-4.2.1-win64-vc14-py27.zip'
  - 7z x omniORB-4.2.1-win64-vc14-py27.zip
  - set OMNI_ROOT=C:\projects\omniORB-%OMNI_VERSION%-win64-vc14-py27
  - svn co http://svn.openrtm.org/OpenRTM-aist/trunk/OpenRTM-aist
  - cd OpenRTM-aist\win32\OpenRTM-aist
  - C:\cygwin64\bin\bash prepare_openrtm.sh
  - env
