clone_folder: c:\projects

environment:
  ARCH: x86_64
  OMNI_VERSION: 4.2.1
  VC_VERSION: 14
  OMNI_ROOT: C:\projects\omniORB-%OMNI_VERSION%-win64-%RTM_VC_VERSION%-py27
  RTM_ARCHIVE: OpenRTM-aist-win32.zip

install:
  - echo "http://openrtm.org/pub/omniORB/win32/omniORB-$env:OMNI_VERSION/omniORB-$env:OMNI_VERSION-win64-vc$env:VC_VERSION-py27.zip"
  - ps: Start-FileDownload "http://openrtm.org/pub/omniORB/win32/omniORB-$env:OMNI_VERSION/omniORB-$env:OMNI_VERSION-win64-vc$env:VC_VERSION-py27.zip"
  - ps: 7z x "omniORB-$env:OMNI_VERSION-win64-vc$env:VC_VERSION-py27.zip"

  - echo "http://openrtm.org:8080/view/00_C++/job/01_openrtm-cxx-dist-trunk/ws/$env:RTM_ARCHIVE"
  - ps: Start-FileDownload "http://openrtm.org:8080/view/00_C++/job/01_openrtm-cxx-dist-trunk/ws/$env:RTM_ARCHIVE"
  - ps: 7z x "$env:RTM_ARCHIVE"

  - env

before_build:
  - cd OpenRTM-aist\ && build.bat

build:

