language: cpp
sudo: required
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang
addons:
  apt:
    packages:
      - subversion
      - gcc
      - g++
      - make
      - automake
      - libtool
      - autoconf
      - uuid-dev
      - libboost-filesystem-dev
      - doxygen
      - libomniorb4-dev
      - omniidl
      - omniorb
      - omniorb-nameserver
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libtool; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen; fi
before_script:
  - svn export http://svn.openrtm.org/OpenRTM-aist/trunk/OpenRTM-aist
  - cd OpenRTM-aist
  - sh build/autogen
  - ./configure --prefix=/usr
script:
  - make
  - sudo make install
