language: cpp
sudo: required
matrix:
  include:
      - os: linux
        compiler: gcc
      - os: linux
        dist: trusty
        compiler: gcc
addons:
  apt:
    packages:
      - subversion
      - gcc
      - g++
      - make
      - uuid-dev
      - libboost-filesystem-dev
      - doxygen
      - libomniorb4-dev
      - omniidl
before_script:
  - svn export http://svn.openrtm.org/OpenRTM-aist/trunk/OpenRTM-aist
  - cd OpenRTM-aist
  - sh build/autogen
  - ./configure --prefix=/usr
script:
  - make
  - sudo make install
