language: cpp
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang
    - os: osx
      osx_image: xcode8.2
      compiler: clang

addons:
  apt:
    packages:
      - subversion
      - gcc
      - g++
      - make
      - automake
      - libtool
      - autoconf
      - uuid-dev
      - libboost-filesystem-dev
      - doxygen
      - libomniorb4-dev
      - omniidl
      - omniorb
      - omniorb-nameserver
      - python-yaml

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libtool; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install omniorb; fi
  - wget http://hp.vector.co.jp/authors/VA000501/qkcc100.zip
  - unzip qkcc100.zip && make && export PATH=$PATH:$PWD/qkc

before_script:
  - svn export http://svn.openrtm.org/OpenRTM-aist/trunk/OpenRTM-aist
  - cd OpenRTM-aist
  - sh build/autogen
  - ./configure --prefix=/usr/local

script:
  - make
  - make dist
  - sudo make install
  - (cd src/ext/logger/fluentbit_stream/ && make && sudo make install)
